services:
  app:
    domainname: www.schedule2.study
    restart: unless-stopped
    build:
      context: ./backend
    ports:
      - mode: ingress
        target: 3000
    deploy:
      resources:
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
